services:
  backend:
    container_name: fastapi_backend
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi/src/.env
    volumes:
      - ./fastapi/src:/fastapi/src

  frontend:
    container_name: react_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/src:/frontend/src